sonar.projectKey=my-django-app
sonar.organization=my-org
sonar.host.url=https://sonarcloud.io
sonar.login=squ_9257400cc8956d45c2d3310dd48bdb1e744a5d8a

# Source files
sonar.sources=.

# Exclude virtual env, migrations, etc.
sonar.exclusions=venv/**,**/migrations/**,**/__pycache__/**

# Python-specific settings
sonar.python.coverage.reportPaths=coverage.xml
